core_user_homepage:
    path:     /
    defaults: { _controller: CoreUserBundle:Default:index }
    
core_user_register:
    path:     /users/
    defaults: { _controller: CoreUserBundle:Users:register}
    methods:  [POST, GET]