services:
#    core_user.example:
#        class: Core\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
# Fixtures services
    Core\UserBundle\Services\CreateAction:
        autowire: true
        public: true
            
        
    AppBundle\DataFixtures\ORM\LoadCountryData:
        tags: [doctrine.fixture.orm]
    