<?php

namespace Core\UserBundle\Repository;

/**
 * countryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class countryRepository extends \Doctrine\ORM\EntityRepository
{
}
